### ISSUE TITLE
CI - build failed

### ISSUE THREAD

**Issue by Undermaken** [latina-in-tech/latina-in-tech.github.io#198]
### Description

Some errors occured while the CI was building the app bundle
here the details https://github.com/latina-in-tech/latina-in-tech.github.io/actions/runs/8763604654/job/24052672359

@salvatorericcardi when you want (no hurries, its Saturday!!!) could you check what appened?

### Steps to reproduce

I guess this command should reproduce the same errors of the CI

`yarn build`

**Comment by salvatorericcardi** [comment]
@Undermaken I see, don't worry because I have already tested before in local env. In fact, sorry if I did not consider that before.

ESLint breaks a little in this case and if we disable the two rules which are appearing in the pipe fail the code works the same. I don't know if it is correct but it works.

**Comment by Undermaken** [comment]
Don't worry, this is our project (yours too, of course) and we're here to teach and learn.

Anyway, **I strongly advise against turning off the eslint rules**. These rules are there to prevent the addition of code that could break functionalities or produce unexpected behaviour. In addition, by disabling these rules, we grant that they can be violated by anyone in future contributions.

I took a look about the building phase and there are several issues. I wan't able to fix them.
If you find any solution, PR is welcome

**Comment by salvatorericcardi** [comment]
I found a clear way to fix the building problems without switch off eslint rules and I started to understand better somethings, thanks to you. I will go ahead with a pr tomorrow so you can test the build too and merge in positive case.

_NOTE_: I also want to warn you about the redirects because in local I noticed I receive error not found (404) then the homepage is redirected to new localized homepage. For me it is not correct, but I don't know if it will be shown in production. 

In your opinion, can I proceed with a pr without problems? In the while, have a good evening. It's saturday for me too and I need a  beer :-P

**Comment by salvatorericcardi** [comment]
@Undermaken this is a video of the first redirect so it's more clear. After that no problem but the first visit in a page has this problem. We can avoid with a loading spinner but I don't know if you have a better solution.

PS I can't load the video directly. Download the zip file, the video is inside. 
[2024-04-24 08-00-54.zip](https://github.com/latina-in-tech/latina-in-tech.github.io/files/15088514/2024-04-24.08-00-54.zip)

**Comment by Undermaken** [comment]
hi @salvatorericcardi sorry but I didn't pay attention on your question

> In your opinion, can I proceed with a pr without problems? In the while, have a good evening. It's saturday for me too and I need a beer :-P

and the answer is: yes you can, of course 😉 

About the redirect problem, you gave me an idea: what about adding a file to handle a custom 404 error and put the logic about redirect there? I did a test and it seems to work fine.
Of course we need to improve the UI, but it does the job.

- create a directory `app`
- then create a file `app/not-found.tsx`
- copy this code in the created file

```ts
'use client';
import React from 'react';
import { i18n } from '../../i18n.config';

const oldPaths = [
  '/',
  '/admins/team',
  '/events/\\d+',
  '/feedback/new',
  '/newsletter',
  '/community'
].map(p => {
  if (p === '/') {
    return new RegExp(`^${p}$`);
  }

  return new RegExp(`^${p}`);
});
const useBackRouteCompatibility = () => {
  React.useEffect(() => {
    const { pathname } = window.location;
    if (oldPaths.some(p => p.test(pathname))) {
      window.location.replace(`/${i18n.defaultLocale}${pathname}`);
    }
  }, []);
};
export default function NotFound() {
  useBackRouteCompatibility();
  const isNeedToRedirect = oldPaths.some(p => p.test(window.location.pathname));
  if (isNeedToRedirect) {
    return 'loading...';
  }
  return (
    <div>
      <h2>Not Found</h2>
    </div>
  );
}
```

here is the result

https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/5d10c134-7f00-4ba6-8c5d-a63cd93a4d92

what do you think?

**Comment by Undermaken** [comment]
fixed by https://github.com/latina-in-tech/latina-in-tech.github.io/issues/198
